export default [
  {
    title: "The Flying Cup Club",
    artist: "Beirut",
    year: 2007,
    runningTime: 39,
    tracks: [
      "A Call to Arms",
      "Nantes",
      "A Sunday Smile",
      "Guyamas Sonora",
      "La banlieue",
      "Cliquot",
      "The Penalty",
      "Forks and Knives (La fête)",
      "In the Mausoleum",
      "Un dernier verre (Pour la route)",
      "Cherbourg",
      "St. Apollonia",
      "The Flying Club Cup",
    ],
  },
  {
    title: "Dookie",
    artist: "Green Day",
    year: 1994,
    runningTime: 39,
    tracks: [
      "Burnout",
      "Having a Blast",
      "Chump",
      "Longview",
      "Welcome to Paradise",
      "Pulling Teeth",
      "Basket Case",
      "She",
      "Sassafras Roots",
      "When I Come Around",
      "Coming Clean",
      "Emenius Sleepus",
      "In the End",
      "F.O.D.",
    ],
  },
  {
    title: "Buhloone Mindstate",
    artist: "De La Soul",
    year: 1993,
    runningTime: 63,
    tracks: [
      "Intro",
      "Eye Patch",
      "En Focus",
      "Patti Dooke",
      "I Be Blowin'",
      "Long Island Wildin'",
      "Ego Trippin' (Part Two)",
      "Paul's Revenge",
      "3 Days Later",
      "Area",
      "I Am I Be",
      "In the Woods",
      "Breakadawn",
      "Dave Has a Problem...Seriously",
      "Stone Age",
    ],
  },
  {
    title: "Graceland",
    artist: "Paul Simon",
    year: 1986,
    runningTime: 43,
    tracks: [
      "The Boy In The Bubble",
      "Graceland",
      "I Know What I Know",
      "Gumboots",
      "Diamonds On The Soles Of Her Shoes",
      "You Can Call Me Al",
      "Under African Skies",
      "Homeless",
      "Crazy Love, Vol. II",
      "That Was Your Mother",
      "All Around The World Or The Myth Of Fingerprints",
    ],
  },
  {
    title: "Sublime",
    artist: "Sublime",
    year: 1996,
    runningTime: 58,
    tracks: [
      "Garden Grove",
      "What I Got",
      "Wrong Way",
      "Same in the End",
      "April 29, 1992 (Miami)",
      "Santeria",
      "Seed",
      "Jailhouse",
      "Pawn Shop",
      "Paddle Out",
      "The Ballad of Johnny Butt",
      "Burritos",
      "Under My Voodoo",
      "Get Ready",
      "Caress Me Down",
      "What I Got (Reprise)",
      "Doin' Time",
    ],
  },
  {
    title: "The Midnight Organ Fight",
    artist: "Frightened Rabbit",
    year: 2008,
    runningTime: 48,
    tracks: [
      "The Modern Leper",
      "I Feel Better",
      "Good Arms vs. Bad Arms",
      "Fast Blood",
      "Old Old Fashioned",
      "The Twist",
      "Bright Pink Bookmark",
      "Head Rolls Off",
      "My Backwards Walk",
      "Keep Yourself Warm",
      "Extrasupervery",
      "Poke",
      "Floating In the Forth",
      "Who'd You Kill Now?",
    ],
  },
  {
    title: "Burnin'",
    artist: "Bob Marley & The Wailers",
    year: 1973,
    runningTime: 49,
    tracks: [
      "Get Up, Stand Up",
      "Hallelujah Time",
      "I Shot the Sheriff",
      "Burnin' and Lootin'",
      "Put It On",
      "Small Axe",
      "Pass It On",
      "Duppy Conqueror",
      "One Foundation",
      "Rastaman Chant",
      "Reincarnated Soul",
      "No Sympathy",
      "The Opressed Song",
    ],
  },
  {
    title: "Come Find Yourself",
    artist: "Fun Lovin' Criminals",
    year: 1996,
    runningTime: 54,
    tracks: [
      "The Fun Lovin' Criminal",
      "Passive/Aggressive",
      "The Grave and the Constant",
      "Scooby Snacks",
      "Smoke 'Em",
      "Bombin' the L",
      "I Can't Get With That",
      "King of New York",
      "We Have All the Time in the World",
      "Bear Hug",
      "Come Find Yourself",
      "Crime and Punishment",
      "Methadonia",
      "10th Street",
    ],
  },
];
